wip: Adds attachment options
optidatacloud/vue-advanced-chat pull request #31
Opened 2023-11-06 18:48 UTC by jeanchilger

- Fixes #30

### :eyes: Visão Geral
Esta PR adiciona a possibilidade de exibid um menu de anexos quando clicar sobre o ícone de upload de arquivo, funcionamento similar ao do _whatsapp_.

### :test_tube: Como Testar
- Será descrito em https://github.com/optidatacloud/optiwork-web-chat/issues/366

2023-11-06 18:55 UTC, jeanchilger commented on src/lib/ChatWindow.vue
> +        @attachment-picker-handler="attachmentPickerHandler"
Além das opções de anexo, resolvi já implementar um evento, agora possivelmente não será utilizado, mas no futuro poderemos utilizá-lo.

2023-11-07 12:49 UTC, arufonsekun commented on src/lib/ChatWindow.vue
> +        @attachment-picker-handler="attachmentPickerHandler"
boa

2023-11-07 12:51 UTC, arufonsekun commented on src/lib/Room/RoomFooter/RoomAttachmentPicker/RoomAttachmentPicker.vue
> +import vClickOutside from '../../../../utils/on-click-outside'
ô... isso aqui é muito moderno, carai, perplecto

2023-11-07 13:45 UTC, arufonsekun requested changes
Parabéns @jeanchilger, o menu ficou muito bunitinho. Código está super bom, nada em específico que eu possa comentar. Só tenho alguns apontamentos/sugestões que gostaria de fazer:

### Sugestões de UI
* A cor da fonte está em preto, acho que poderia ser cinza (dá pra ver a cor da fonte dos outros dropdowns, não lembro bem certo de qual variável estamos pegando essa cor). Como esse menu tá dentro do VAC e a cor da fonte é o BS que seta, pode ser paia de pegar ela, se for o caso seta a cor na unha e vida que segue, sem stress;
 
![image](https://github.com/optidatacloud/vue-advanced-chat/assets/19571204/cb212864-32bd-48e6-9161-c881193ee737)

* Acho que seria interessante também colocar um efeito de hover nas opções desse menu, só pra ficar de acordo com os outros dropdowns (desculpa a chatice);
* Eu não cheguei a testar esse menu no modo dark pq meu Webapp tá quebrado, acho que seria interessante ver como ele fica nesse modo;
* Acho que seria interessante também colocar uma opção pra abrir a câmera nesse menu, mas daí pode ser _leak_ de scopo, se pá dá fazer numa issue nova. Pode decidir como fica melhor pra ti @jeanchilger;

### Testes no mobile
* Testei o menu no mobile e infelizmente deu bode;
* Todas as opções abrem a câmera ao invés do file explorer;
* Tempo atrás resolvi um bug no mobile que o botão de anexar do Chat sempre abria a câmera, talvez pode te ajudar: https://github.com/optidatacloud/optiwork-web-chat/pull/367;

2023-11-07 17:03 UTC, jeanchilger commented
EDIT: Opção de abrir camera adicionada no mobile somente. Criação da funcionalidade no web ficará para o futuro.

2023-11-08 17:08 UTC, arufonsekun approved these changes
Fabuloso!! 

![](https://media1.giphy.com/media/lMVNl6XxTvXgs/giphy.gif?cid=ecf05e47b6gye8tpqr5py99iwidean0lgh48jcsijfx43dij&ep=v1_gifs_related&rid=giphy.gif&ct=g)

2023-11-10 14:26 UTC, Dovyski approved these changes
Excelente! 🚀👏 ❤️ Só ajustar os conflitos e estamos prontos para merge, @jeanchilger

2023-11-10 17:34 UTC, merged