feat: Filter users by email (issue #55)
optidatacloud/vue-advanced-chat pull request #56
Opened 2024-03-27 13:45 UTC by arufonsekun

### Descrição 📝 
* Ajusta para que o model room tenha o campo email;
* Ajusta a função de filtro pra que ela aceite um array de campos a serem filtrados;
* resolves #55

### Como testar 🐛 
* Testar aqui: https://github.com/optidatacloud/optiwork-web-chat/pull/679

2024-03-27 13:55 UTC, marconiryan requested changes
Muito bom :fire: :rocket: 

Pedi um ajuste :+1:

2024-03-27 13:55 UTC, marconiryan commented on src/utils/filter-items.js
> +			}, false);
Tem que fazer um esforço muito grande para entender o que é `v` e `acc`. Se conseguir deixar com um nome mais significativo

2024-03-27 14:01 UTC, Fernando-Magnabosco commented on src/utils/filter-items.js
> +			}, false);
Nesse mesmo sentido, acho que no lugar desses `reduce` cabiam `some`, n? acho que pra esse tipo de coisa o `some` é mais performático já que ele para no primeiro valor `truthy`

2024-03-27 14:24 UTC, arufonsekun commented on src/utils/filter-items.js
> +			}, false);
> Tem que fazer um esforço muito grande para entender o que é `v` e `acc`. Se conseguir deixar com um nome mais significativo

Esse `v` vem da lib, daí não me preocupei mt (mas posso mudar). O `acc` real foi meio poucas ideias, vou ajustar 😅

2024-03-27 14:26 UTC, jeanchilger approved these changes
Nada a acrescentar além do que já foi discutido.

2024-03-27 14:26 UTC, arufonsekun commented on src/utils/filter-items.js
> +			}, false);
> Nesse mesmo sentido, acho que no lugar desses `reduce` cabiam `some`, n? acho que pra esse tipo de coisa o `some` é mais performático já que ele para no primeiro valor `truthy`

meu é vdd, sequelei, pq usei `reduce` só Deus sabe, kkkkkk, vou ajustar, obrigado senhores

2024-03-27 14:44 UTC, Fernando-Magnabosco commented on src/utils/filter-items.js
> +			}, false);
acho que acc é o nome padrão do arg do reduce

2024-03-27 14:45 UTC, Fernando-Magnabosco approved these changes

2024-03-27 17:12 UTC, marconiryan approved these changes

2024-03-28 11:54 UTC, arufonsekun commented
Obrigado pelo review gente, mergeando 🕊️

2024-03-28 11:55 UTC, merged