feat: Emits event when user clicks on message username (issue #62)
optidatacloud/vue-advanced-chat pull request #65
Opened 2024-04-03 19:04 UTC by arufonsekun

### Descrição 📝 
* Faz os ajustes necessários para que o VAC emita um evento quando houver um `click` no nome de usuário em uma mensagem;
* resolves #62;

### Prévia 👀 
* Click no `Beltrano Silva ` trigga um evento que uso pra abrir a conversa no Optiwork Chat;

![](https://raw.githubusercontent.com/optidatacloud/vue-advanced-chat/fda8c0c2bbe7b0a86bf47bdbeebed4fbe5aae3f6/docs/username-on-message.png)

### Como testar 🐛 
* Testar [aqui](url);

2024-04-03 19:24 UTC, jeanchilger requested changes
Muto bom!!! Deixei uma sugestão, nada grave, fica a seu critério segui-la ou não.

2024-04-03 19:24 UTC, jeanchilger commented on README.md
> +| `open-user-room`(19)                  | `{ user }`                                                                 | Clicked on message username                     |
Acho que poderíamos utilizar, no nome do evento e internamente no VAC, a ação que irá ocorrer ao invés da consequência da ação. Neste caso, você utilizaria algo como `click-user-room` ou `click-message-username`.

Assim fica mais claro do que o evento se trata e fica ao encargo de quem irá utilizá-lo definir uma ação mais específica. Podemos adotar esse padrão daqui pra frente, se achar pertinente.

2024-04-03 20:41 UTC, arufonsekun commented on README.md
> +| `open-user-room`(19)                  | `{ user }`                                                                 | Clicked on message username                     |
Gostei de `click-message-username`, vou ajustar, obrigado pela sugestão

2024-04-04 11:56 UTC, jeanchilger commented on src/lib/ChatWindow.vue
> +				@click-message-username="$emit('click-message-username', $event)"
Daria pra aproveitar e adicionar esse evento no `emits` desse mesmo componente, igual você fez nos demais.

2024-04-04 11:57 UTC, MatheusZuchiBalbinot approved these changes
Simplesmente, M-A-R-A-V-I-L-H-O-S-O, mano @arufonsekun. Show de bola 🐲

2024-04-04 11:58 UTC, MatheusZuchiBalbinot commented
> Como testar 🐛
> - Testar [aqui](https://github.com/optidatacloud/vue-advanced-chat/pull/url);

Só um adendo, esse `Como testar` não está com um link válido.

2024-04-04 14:40 UTC, marconiryan approved these changes
Muito bom :rocket:

2024-04-04 17:15 UTC, jeanchilger commented
Já pode ser mergeado @arufonsekun.

2024-04-04 17:15 UTC, merged

2024-04-04 17:15 UTC, jeanchilger commented
Mergeei :clown_face: