Download button on media preview (issue #765)
optidatacloud/vue-advanced-chat pull request #78
Opened 2024-07-08 17:57 UTC by DouglasKosvoski

### Descrição
- Esse PR tem como objetivo adicionar uma nova funcionalidade na visualização de mídia do chat (issue [#765](https://github.com/optidatacloud/optiwork-chat/issues/765) ) , adicionando um botão de "Download" no canto superior direito, similar ao que já é feito para o visualizador de anexos do drive.

### Prévia
- Captura de tela mostrando o botão:
![image](https://github.com/optidatacloud/vue-advanced-chat/assets/35408292/377300b9-0bd7-4ec6-aecf-c20a5e884516)

### Como testar:
- Carregue uma imagem em qualquer conversa e envie, clique na imagem carregada para expandir seu conteúdo e, finalmente, pressione o botão de download. Se feito corretamente, a imagem será baixada para o seu navegador.

2024-07-08 21:31 UTC, SWE3T approved these changes
Parabén pelo primeiro PR, primeiro de muitos 🥳🎉🚀!  Muito bom!

2024-07-08 21:31 UTC, SWE3T commented on src/lib/MediaPreview/MediaPreview.scss
> +		transform: scale(1) !important;
Acredito que essa regra não seja necessária.

2024-07-09 11:55 UTC, larimones commented on src/lib/MediaPreview/MediaPreview.scss
> +		color: var(--chat-color-button);
Uma sugestão, eu deixaria roxo como é o do drive : 
![image](https://github.com/optidatacloud/vue-advanced-chat/assets/64796362/65e9cfb4-b9c7-4a12-ab2c-1cecfa1254ae)
pra ficar padronizado

2024-07-09 11:56 UTC, larimones approved these changes
Parabéns pelo Lindo PR ✨ só deixei uma sugestão!

2024-07-09 11:58 UTC, Dovyski requested changes
Primeiro PR, uhulll! 🥳🔥🚀👏 Muito bom, @DouglasKosvoski !

Eu só pedi uma alteração de indentação para que possamos ter um melhor registro de alterações. De resto, está excelente!

2024-07-09 11:58 UTC, Dovyski commented on src/lib/MediaPreview/MediaPreview.scss
> +	}
Aqui parece que houve uma troca na quantidade de espaços na indentação (eram 2 e passou a ser 1). Nossa indentação oficial são 4 espaços (pode configurar o VSCode para substituir um tab por 4 espaços).

No caso do VAC, como é algo externo, vamos tentar minimizar as alterações de indentação para que o registro fique só do que foi realmente alterado. Por isso, por favor, restaura a indentação antiga do arquivo (2 espaços) para que só as tuas reais alterações apareçam no diff.

2024-07-09 12:30 UTC, marconiryan requested changes
Muito bomm :rocket: :fire: 

Parabens pelo teu primeiro PR :clap: 

Deixei alguns uns comentarios

2024-07-09 12:30 UTC, marconiryan commented on src/lib/MediaPreview/MediaPreview.scss
> +		}
Eu particularmente não gosto quando eu passo o mouse por cima e botão se mexe. Se tu quiser seguir o padrão do Drive, so colocar um `box-shadow`

![image](https://github.com/optidatacloud/vue-advanced-chat/assets/86175804/cb701737-e7c1-4d4b-b376-7b54ca0b40d2)


```suggestion
```

2024-07-09 12:48 UTC, marconiryan commented on src/lib/MediaPreview/MediaPreview.scss
> +		padding: 0.375rem 0.75rem;
Tu pode usar como inspiração o [modal do drive](https://github.com/optidatacloud/optiwork-app/blob/dev/resources/views/modals/file-view.blade.php). Nele aparecem esses botões de `download` e `close`.

O conteudo é processado pelos arquivos [content-handlers](https://github.com/optidatacloud/optiwork-app/blob/dev/resources/js/drive/content-handlers/manager.js) e [image/main.js](https://github.com/optidatacloud/optiwork-app/blob/dev/resources/js/drive/content-handlers/image/main.js). (Referecia apenas)

2024-07-09 13:32 UTC, Dovyski commented on src/lib/MediaPreview/MediaPreview.scss
> +		}
Vamos tentar seguir ao máximo o padrão das aplicações já existentes. Como o @marconiryan falou, acho legal colocar o box-shadow no hover ao invés do scale.

2024-07-09 13:33 UTC, Dovyski requested changes

2024-07-09 13:33 UTC, Dovyski commented on src/lib/MediaPreview/MediaPreview.scss
> +		color: var(--chat-color-button);
Reforçando, vamos usar a mesma cor do drive aqui.

2024-07-09 19:54 UTC, Dovyski approved these changes
Obrigado pelas alterações! ❤️

2024-07-09 19:55 UTC, Dovyski commented
Como os pedidos do @marconiryan foram atendidos, vou fazer merge já.

2024-07-09 19:55 UTC, merged