feat: click on message avatar to open side menu (issue #863 pr #82)
optidatacloud/vue-advanced-chat pull request #82
Opened 2024-07-16 21:25 UTC by DouglasKosvoski

> Resolve:
> - https://github.com/optidatacloud/optiwork-chat/issues/863

### Descrição
- Esse PR adiciona a funcionalidade de copiar o conteúdo de uma mensagem através do menu de ações.

### Prévia
- Captura de tela mostrando a ação de copiar:
![image](https://github.com/user-attachments/assets/d63b45a1-b0a4-4ea0-ae7f-167f74b17540)

### Como testar:
- Abra uma conversa com outra pessoa (individual ou em grupo) e clique nas opções da mensagem, se a imagem contiver um conteúdo texto a botão estará disponível e ao clicar o conteúdo deve ser copiado para a área de transferência.

Fix: https://github.com/optidatacloud/optiwork-chat/issues/863

2024-07-17 14:08 UTC, Dovyski approved these changes
Topster! 🚀 👏

2024-07-17 14:12 UTC, letyrsl requested changes
Muito bom 🥳 🎉 
Deixei um comentário pra debatermos sobre, pq não sei se é a melhor opção aqui

2024-07-17 14:12 UTC, letyrsl commented on src/lib/Room/RoomMessage/MessageActions/MessageActions.vue
> +            <div class="vac-menu-item" :class="{ 'vac-action-disabled': action.name === 'copyMessage' && message.content === '' }" @click="messageActionHandler(action)">
Talvez isso não seja muito escalável...
Tava tentando pensar em fazer algo mais genérico pra isso, mas como não tenho muito conhecimento em Vue e no Chat em si, não vou saber falar uma solução muito boa.

O que pensei foi talvez em criar uma flag nas actions, algo tipo `disableIfContentIsNull`, e aí fazer a condição assim:

`:class="{ 'vac-action-disabled': action.disableIfContentIsNull && message.content === '' }"`

2024-07-17 20:44 UTC, DouglasKosvoski commented on src/lib/Room/RoomMessage/MessageActions/MessageActions.vue
> +            <div class="vac-menu-item" :class="{ 'vac-action-disabled': action.name === 'copyMessage' && message.content === '' }" @click="messageActionHandler(action)">
Adorei a sugestão @letyrsl, acabei de adicionar essa alteração, muito obrigado.

~~Tbm não tenho experiência em Vue :v~~

2024-07-18 11:32 UTC, letyrsl approved these changes
Ta topp, parabéns 🚀 💯

2024-07-18 16:32 UTC, jeanchilger approved these changes
Muito bom :rocket:

2024-07-18 18:13 UTC, merged